FROM domain-base

COPY domain_schema/ /src

WORKDIR src
RUN pip install pipenv
RUN pipenv install --dev --system --deploy

EXPOSE 8030

CMD python manage.py migrate core && python manage.py runserver 0.0.0.0:8030

